name: "[DEBUG] Flutter Test, Build"
on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  flutter_build_web:
    name: Build Flutter Web
    runs-on: ubuntu-latest
    environment: debug-environment

    steps:
      - uses: actions/checkout@v4

      - name: Env configuration
        uses: ./.github/actions/create-env-files
        with:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
          FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ vars.FIREBASE_DATABASE_URL }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
          GOOGLE_LOGIN_WEB_CLIENT_ID: ${{ vars.GOOGLE_LOGIN_WEB_CLIENT_ID }}
          MEASUREMENT_ID: ${{ vars.MEASUREMENT_ID }}
          FIREBASE_VAPID_KEY: ${{ secrets.FIREBASE_VAPID_KEY }}
          log: "debug"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - name: Build Flutter Web (Debug)
        run: flutter build web --dart-define=DISPLAY_VERSION_TAG=true --dart-define-from-file="env/.env" --profile


      - name: Display build/web items
        run: ls -la build/web

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-web
          path: build/web
          retention-days: 1
          include-hidden-files: true

  flutter_test:
    name: Test Flutter with Coverage report
    runs-on: ubuntu-latest
    environment: debug-environment

    steps:
      - uses: actions/checkout@v4

      - name: Env configuration
        uses: ./.github/actions/create-env-files
        with:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
          FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ vars.FIREBASE_DATABASE_URL }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
          GOOGLE_LOGIN_WEB_CLIENT_ID: ${{ vars.GOOGLE_LOGIN_WEB_CLIENT_ID }}
          MEASUREMENT_ID: ${{ vars.MEASUREMENT_ID }}
          FIREBASE_VAPID_KEY: ${{ secrets.FIREBASE_VAPID_KEY }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter test --machine --coverage --dart-define-from-file="env/.env"

  #    # Publish coverage report to GitHub
  #      - name: Publish coverage report
  #        uses: coverallsapp/github-action@v1.1.2
  #        with:
  #        github-token: ${{ secrets.GITHUB_TOKEN }}
  #        path-to-lcov: coverage/lcov.info


#  flutter_deploy_web:
#    name: Deploy Flutter Web
#    environment: debug-environment
#    runs-on: ubuntu-latest
#    needs: [ flutter_test, flutter_build_web ]
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Download build artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: flutter-build-web
#          path: build/web
#
#        # TOKEN SETUP GUIDE: https://github.com/FirebaseExtended/action-hosting-deploy
#      - uses: FirebaseExtended/action-hosting-deploy@v0
#        with:
#          repoToken: '${{ secrets.GITHUB_TOKEN }}'
#          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
#          projectId: '${{ vars.FIREBASE_PROJECT_ID }}'
#          channelId: live